CREATE DATABASE songs;
USE songs;

CREATE TABLE song_data(
    song_id INT NOT NULL AUTO_INCREMENT,
    song_title VARCHAR(255), 
    song_url_part VARCHAR(255),
    PRIMARY KEY (song_id)
);

INSERT INTO song_data(song_title, song_url_part)
VALUES
("Jehovah's Attributes", "1-jehovahs-attributes"),
("Jehovah Is Your Name", "2-jehovah-is-your-name"),
("Our Strength, Our Hope, Our Confidence", "3-our-strength-our-hope-our-confidence"),
("“Jehovah Is My Shepherd”", "4-jehovah-is-my-shepherd"),
("God’s Wondrous Works", "5-gods-wondrous-works"),
("The Heavens Declare God’s Glory", "6-the-heavens-declare-gods-glory"),
("Jehovah, Our Strength", "7-jehovah-our-strength"),
("Jehovah Is Our Refuge", "8-jehovah-is-our-refuge"),
("Jehovah Is Our King!", "9-jehovah-is-our-king"),
("Praise Jehovah Our God!", "10-praise-jehovah-our-god"),
("Creation Praises God", "11-creation-praises-god"),
("Great God, Jehovah", "12-great-god-jehovah"),
("Christ, Our Model", "13-christ-our-model"),
("Praising Earth’s New King", "14-praising-earths-new-king"),
("Praise Jehovah’s Firstborn!", "15-praise-jehovahs-firstborn"),
("Praise Jah for His Son, the Anointed", "16-praise-jah-for-his-son-the-anointed"),
("“I Want To”", "17-i-want-to"),
("Grateful for the Ransom", "18-grateful-for-the-ransom"),
("The Lord’s Evening Meal", "19-the-lords-evening-meal"),
("You Gave Your Precious Son", "20-you-gave-your-precious-son"),
("Keep On Seeking First the Kingdom", "21-keep-on-seeking-first-the-kingdom"),
("The Kingdom Is in Place—Let It Come!", "22-the-kingdom-is-in-place-let-it-come"),
("Jehovah Begins His Rule", "23-jehovah-begins-his-rule"),
("Come to Jehovah’s Mountain", "24-come-to-jehovahs-mountain"),
("A Special Possession", "25-a-special-possession"),
("You Did It for Me", "26-you-did-it-for-me"),
("The Revealing of God’s Sons", "27-the-revealing-of-gods-sons"),
("Gaining Jehovah’s Friendship", "28-gaining-jehovahs-friendship"),
("Living Up to Our Name", "29-living-up-to-our-name"),
("My Father, My God and Friend", "30-my-father-my-god-and-friend"),
("Oh, Walk With God!", "31-oh-walk-with-god"),
("Take Sides With Jehovah!", "32-take-sides-with-jehovah"),
("Throw Your Burden on Jehovah", "33-throw-your-burden-on-jehovah"),
("Walking in Integrity", "34-walking-in-integrity"),
("“Make Sure of the More Important Things”", "35-make-sure-of-the-more-important-things"),
("We Guard Our Hearts", "36-we-guard-our-hearts"),
("Serving Jehovah Whole-Souled", "37-serving-jehovah-whole-souled"),
("He Will Make You Strong", "38-he-will-make-you-strong"),
("Make a Good Name With God", "39-make-a-good-name-with-god"),
("To Whom Do We Belong?", "40-to-whom-do-we-belong"),
("Please Hear My Prayer", "41-please-hear-my-prayer"),
("The Prayer of God’s Servant", "42-the-prayer-of-gods-servant"),
("A Prayer of Thanks", "43-a-prayer-of-thanks"),
("A Prayer of the Lowly One", "44-a-prayer-of-the-lowly-one"),
("The Meditation of My Heart", "45-the-meditation-of-my-heart"),
("We Thank You, Jehovah", "46-we-thank-you-jehovah"),
("Pray to Jehovah Each Day", "47-pray-to-jehovah-each-day"),
("Daily Walking With Jehovah", "48-daily-walking-with-jehovah"),
("Making Jehovah’s Heart Glad", "49-making-jehovahs-heart-glad"),
("My Prayer of Dedication", "50-my-prayer-of-dedication"),
("To God We Are Dedicated!", "51-to-god-we-are-dedicated"),
("Christian Dedication", "52-christian-dedication"),
("Preparing to Preach", "53-preparing-to-preach"),
("“This Is the Way”", "54-this-is-the-way"),
("Fear Them Not!", "55-fear-them-not"),
("Make the Truth Your Own", "56-make-the-truth-your-own"),
("Preaching to All Sorts of People", "57-preaching-to-all-sorts-of-people"),
("Searching for Friends of Peace", "58-searching-for-friends-of-peace"),
("Praise Jah With Me", "59-praise-jah-with-me"),
("It Means Their Life", "60-it-means-their-life"),
("Forward, You Witnesses!", "61-forward-you-witnesses"),
("The New Song", "62-the-new-song"),
("We’re Jehovah’s Witnesses!", "63-were-jehovahs-witnesses"),
("Sharing Joyfully in the Harvest", "64-sharing-joyfully-in-the-harvest"),
("Move Ahead!", "65-move-ahead"),
("Declare the Good News", "66-declare-the-good-news"),
("“Preach the Word”", "67-preach-the-word"),
("Sowing Kingdom Seed", "68-sowing-kingdom-seed"),
("Go Forward in Preaching the Kingdom!", "69-go-forward-in-preaching-the-kingdom"),
("Search Out Deserving Ones", "70-search-out-deserving-ones"),
("We Are Jehovah’s Army!", "71-we-are-jehovahs-army"),
("Making Known the Kingdom Truth", "72-making-known-the-kingdom-truth"),
("Grant Us Boldness", "73-grant-us-boldness"),
("Join in the Kingdom Song!", "74-join-in-the-kingdom-song"),
("“Here I Am! Send Me!”", "75-here-i-am-send-me"),
("How Does It Make You Feel?", "76-how-does-it-make-you-feel"),
("Light in a Darkened World", "77-light-in-a-darkened-world"),
("“Teaching the Word of God”", "78-teaching-the-word-of-god"),
("Teach Them to Stand Firm", "79-teach-them-to-stand-firm"),
("“Taste and See That Jehovah Is Good”", "80-taste-and-see-that-jehovah-is-good"),
("The Life of a Pioneer", "81-the-life-of-a-pioneer"),
("“Let Your Light Shine”", "82-let-your-light-shine"),
("“From House to House”", "83-from-house-to-house"),
("Reaching Out", "84-reaching-out"),
("Welcome One Another", "85-welcome-one-another"),
("We Must Be Taught", "86-we-must-be-taught"),
("Come! Be Refreshed", "87-come-be-refreshed"),
("Make Me Know Your Ways", "88-make-me-know-your-ways"),
("Listen, Obey, and Be Blessed", "89-listen-obey-and-be-blessed"),
("Encourage One Another", "90-encourage-one-another"),
("Our Labor of Love", "91-our-labor-of-love"),
("A Place Bearing Your Name", "92-a-place-bearing-your-name"),
("Bless Our Meeting Together", "93-bless-our-meeting-together"),
("Grateful for God’s Word", "94-grateful-for-gods-word"),
("The Light Gets Brighter", "95-the-light-gets-brighter"),
("God’s Own Book—A Treasure", "96-gods-own-book-a-treasure"),
("Life Depends on God’s Word", "97-life-depends-on-gods-word"),
("The Scriptures—Inspired of God", "98-the-scriptures-inspired-of-god"),
("Myriads of Brothers", "99-myriads-of-brothers"),
("Receive Them With Hospitality", "100-receive-them-with-hospitality"),
("Working Together in Unity", "101-working-together-in-unity"),
("Assist Those Who Are Weak", "102-assist-those-who-are-weak"),
("Shepherds​—Gifts in Men", "103-shepherds-gifts-in-men"),
("God’s Gift of Holy Spirit", "104-gods-gift-of-holy-spirit"), 
("God Is Love", "105-god-is-love"),
("Cultivating the Quality of Love", "106-cultivating-the-quality-of-love"),
("The Divine Pattern of Love", "107-the-divine-pattern-of-love"),
("God’s Loyal Love", "108-gods-loyal-love"),
("Love Intensely From the Heart", "109-love-intensely-from-the-heart"),
("The Joy of Jehovah", "110-the-joy-of-jehovah"),
("Our Reasons for Joy", "111-our-reasons-for-joy"),
("Jehovah, God of Peace", "112-jehovah-god-of-peace"),
("Our Possession of Peace", "113-our-possession-of-peace"),
("Exercise Patience", "114-exercise-patience"),
("Gratitude for Divine Patience", "115-gratitude-for-divine-patience"),
("The Power of Kindness", "116-the-power-of-kindness"),
("The Quality of Goodness", "117-the-quality-of-goodness"),
("Give Us More Faith", "118-give-us-more-faith"),
("We Must Have Faith", "119-we-must-have-faith"),
("Imitate Christ’s Mildness", "120-imitate-christs-mildness"),
("We Need Self-Control", "121-we-need-self-control"),
("Be Steadfast, Immovable!", "122-be-steadfast-immovable"),
("Loyally Submitting to Theocratic Order", "123-loyally-submitting-to-theocratic-order"),
("Ever Loyal", "124-ever-loyal"),
("Happy Are the Merciful!", "125-happy-are-the-merciful"),
("Stay Awake, Stand Firm, Grow Mighty", "126-stay-awake-stand-firm-grow-mighty"),
("The Sort of Person I Should Be", "127-the-sort-of-person-i-should-be"),
("Enduring to the End", "128-enduring-to-the-end"),
("We Will Keep Enduring", "129-we-will-keep-enduring"),
("Be Forgiving", "130-be-forgiving"),
("What God Has Yoked Together", "131-what-god-has-yoked-together"),
("Now We Are One", "132-now-we-are-one"),
("Worship Jehovah During Youth", "133-worship-jehovah-during-youth"),
("Children Are a Trust From God", "134-children-are-a-trust-from-god"),
("Jehovah’s Warm Appeal: Be Wise, My Son", "135-jehovahs-warm-appeal-be-wise-my-son"),
("A Perfect Wage From Jehovah", "136-a-perfect-wage-from-jehovah"),
("Faithful Women, Christian Sisters", "137-faithful-women-christian-sisters"),
("Beauty in Gray-Headedness", "138-beauty-in-gray-headedness"),
("See Yourself When All Is New", "139-see-yourself-when-all-is-new"),
("Life Without End​—At Last!", "140-life-without-end-at-last"),
("The Miracle of Life", "141-the-miracle-of-life"),
("Holding Fast to Our Hope", "142-holding-fast-to-our-hope"),
("Keep Working, Watching, and Waiting", "143-keep-working-watching-and-waiting"),
("Keep Your Eyes on the Prize!", "144-keep-your-eyes-on-the-prize"),
("God’s Promise of Paradise", "145-gods-promise-of-paradise"),
("Making All Things New", "146-making-all-things-new"),
("Life Everlasting Is Promised", "147-life-everlasting-is-promised"),
("Jehovah Provides Escape", "148-jehovah-provides-escape"),
("A Victory Song", "149-a-victory-song"),
("Seek God for Your Deliverance", "150-seek-god-for-your-deliverance"),
("He Will Call", "151-he-will-call"),
("A Place That Will Bring You Praise", "152-a-place-that-will-bring-you-praise"),
("Give Me Courage", "153-give-me-courage"),
("Unfailing Love", "154-unfailing-love"),
("Our Joy Eternally", "155-our-joy-eternally"),
("With Eyes of Faith", "156-with-eyes-of-faith"),
("Peace at Last", "157-peace-at-last"),
("It Will Not Be Late", "158-it-will-not-be-late");



 UPDATE song_data SET song_title = "We're Jehovah's Witnesses!" WHERE song_id = 63;

